### ISSUE TITLE
Include source code

### ISSUE THREAD

**Issue by mozeryansky** [theeluwin/Kara#1]
Thanks for sharing your plugin. I did look through the compiled strings, and everything looks fine, but it'd be nice to include the source code of the plugin as well.

**Comment by theeluwin** [comment]
You mean this? https://github.com/theeluwin/Kara/blob/master/Kara.codaplugin/Contents/Resources/A1048D2B-34A3-46AC-87CE-AA96FCE394F1/kara.py

**Comment by mozeryansky** [comment]
I meant the source for the compiled plugin itself:
https://github.com/theeluwin/Kara/blob/master/Kara.codaplugin/Contents/MacOS/CodaScriptPlugIn

I assume you may have used a generator to created it.

**Comment by theeluwin** [comment]
Well, yes I've used the generator but not quite sure how to import source withing. For instance, https://github.com/panicinc/CodaPluginKit/blob/master/Script%20Plug-ins/Capitalization.codaplugin/Contents/MacOS/CodaScriptPlugIn

**Comment by mozeryansky** [comment]
No problem on the source, I was just wondering how the plugin was made. Thanks for the link!
